image: node:6.9.4
pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: test  
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master